---
- name: Configure EC2 instance via SSM
  hosts: tag_environment__staging
  gather_facts: yes
  connection: amazon.aws.aws_ssm  # Correct SSM connection plugin
  become: yes

  tasks:
    - name: Check hostname via SSM
      amazon.aws.aws_ssm:
        targets: "{{ inventory_hostname }}"
        document_name: AWS-RunShellScript
        commands:
          - hostname

    - name: Install nginx
      amazon.aws.aws_ssm:
        targets: "{{ inventory_hostname }}"
        document_name: AWS-RunShellScript
        commands:
          - sudo yum install -y nginx

    - name: Ensure nginx is running
      amazon.aws.aws_ssm:
        targets: "{{ inventory_hostname }}"
        document_name: AWS-RunShellScript
        commands:
          - sudo systemctl enable nginx
          - sudo systemctl start nginx
