---
- name: Configure EC2 instance via SSM
  hosts: tag_environment__staging
  gather_facts: yes
  connection: amazon.aws.aws_ssm  # Correct SSM connection plugin
  become: yes

  tasks:
    
    - name: Install nginx
      commands:
          - sudo yum install -y nginx

    - name: Ensure nginx is running
      commands:
          - sudo systemctl enable nginx
          - sudo systemctl start nginx
