---
- name: Configure EC2 instance via SSM
  hosts: tag_environment__staging
  gather_facts: yes
  connection: amazon.aws.aws_ssm
  become: yes

  tasks:
    
    - name: Install nginx via SSM
      package:
        
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure nginx is running via SSM
      
      service:
        name: nginx
        state: started
        enabled: yes