---
- name: Configure EC2 instance via SSM
  hosts: tag_environment__staging
  gather_facts: yes
  connection:  community.aws.aws_ssm  # Use the AWS SSM connection plugin for Ansible
  become: yes


  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
